SELECT date_format(B.SALES_DATE,'%Y') AS YEAR, 
date_format(B.SALES_DATE,'%m') AS MONTH, 
count(DISTINCT B.USER_ID) AS PUCHASED_USERS, 
ROUND(count(DISTINCT B.USER_ID)/(SELECT count(USER_ID) FROM USER_INFO WHERE JOINED LIKE '2021%'),1) AS PUCHASED_RATIO
FROM USER_INFO A JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
WHERE A.JOINED LIKE '2021%'
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC