SELECT B.USER_ID, B.NICKNAME, sum(A.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD A RIGHT JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
WHERE STATUS = 'DONE'
GROUP BY B.USER_ID
HAVING sum(A.PRICE) >= 700000
ORDER BY TOTAL_SALES